### PR TITLE
Fix WebSocket timeout

### LINKED ISSUE #30: Add useful WS close messages
When the WebSocket gets closed by `patches`, it should send a close message to the client to help with debugging.

### LINKED ISSUE #31: Fix WebSocket connections closing after a minute
Probably need to send some kind of keep-alive/ping-pong message every once in a while to prevent the connection from closing.

### PR DESCRIPTION
**Pull request by igorveselinovic**
Resolves #31 
Resolves #30 

Now whenever anything is written to/read from a client WebSocket connection (besides closing messages), a finite timeout is sent. Previously there was an infinite wait. Also added ping-pong logic, so if nothing is getting written to the WebSocket for 54 seconds, then a ping message will be sent and a pong response will be expected.

Also added more useful WebSocket closing messages in the connection setup phase.

### CODE REVIEW

File: websockets/client.go [hunk 1]
```diff
@@ -3,10 +3,23 @@ package websockets
 import (
 	"log"
 	"patches/protocol"
+	"time"
 
+	"github.com/gorilla/websocket"
```
Comment (Thao-Tran) [inline websockets/client.go]: Isn't this the same library as the one below?

Comment (igorveselinovic) [reply websockets/client.go]: Yeah, that's a copy-paste mistake.

**Review by Thao-Tran — APPROVED** [review]
